name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.19.0"
      - name: Install node modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Run TypeScript type check
        run: npm run tsc --noEmit
      # - name: Run tests
      #   run: npm run test:ci
      - name: Build Next.js project
        run: npm run build
