name: tests

on:
  push:
    paths:
      - "apps/web/**"
      - ".github/workflows/main.yml" # ワークフロー自体の変更もトリガーに含める

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.19.0"
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # pnpmのバージョンを指定
      - name: Install dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm turbo run lint --filter=@tarrot/web...
      - name: Run TypeScript type check
        run: pnpm turbo run type-check --filter=@tarrot/web...
      - name: Run tests
        run: pnpm turbo run test --filter=@tarrot/web... # test スクリプトを想定 (test:ci がなければ test)
      - name: Build projects
        run: pnpm turbo run build --filter=@tarrot/web...
